### ISSUE TITLE
Cannot play music discs without crashing the server

### ISSUE THREAD

**Issue by dewrot** [Merith-TK/cc-restitched#48]
## Useful information to include:
 - Minecraft version : 1.16.5/Fabric
 - CC: Restitched version: 1.95.3-beta
 - Detailed reproduction steps: This bit of code works in singleplayer but not multiplayer

> drive = peripheral.wrap("top")
drive.playAudio()`

[crash-2021-06-03_09.42.06-server.txt](https://github.com/Merith-TK/cc-restitched/files/6592435/crash-2021-06-03_09.42.06-server.txt)

**Comment by Merith-TK** [comment]
I am able to reproduce this with latest code as of  [This Commit](https://github.com/Merith-TK/cc-restitched/commit/01d7aaf06280700457377587ee28093daeb8bf8c)

Thanks for letting us know! This would be really bad if a player wanted to play music all the time and put this in the startup.lua

**Comment by Merith-TK** [comment]
also potentially relevant
![image](https://user-images.githubusercontent.com/10422110/120668867-bc8ad480-c443-11eb-8381-e3e8d8a90a57.png)

@Toad-Dev  Example Peripheral
Advanced Computer
Speaker
Disk Drive,
Advanced Turtle

**Comment by SquidDev** [comment]
You're going to need to get the private field directly rather than using `getSound`, as that's stripped from the server jar. Compare what CC:T does:

https://github.com/SquidDev-CC/CC-Tweaked/blob/c45221a2d0e91eaebabc495a817c009e6dc6b321/src/main/java/dan200/computercraft/shared/media/items/RecordMedia.java#L55

vs CC:R

https://github.com/Merith-TK/cc-restitched/blob/01d7aaf06280700457377587ee28093daeb8bf8c/src/main/java/dan200/computercraft/shared/media/items/RecordMedia.java#L45

**Comment by Merith-TK** [comment]
> You're going to need to get the private field directly rather than using `getSound`, as that's stripped from the server jar. Compare what CC:T does:

Will look into it, thanks for pointing this out

**Comment by Toad-Dev** [comment]
Sounds like a job for a MusicDiscItemAccessor 🦆
